travis:
  secure:
    BINSTAR_TOKEN: ZSNnDRJj8ajp+edH263H0RvejPe8kakqIjir9zeFKKxLx3gJlLuzfCD5P4g1TBeDhWSZs7zG5n91nu1I7ufsxRILlBq2T/amZbSoQLolEbOUh4IT0VtpNXR2l2EmDG3vpzbiAH68SinrnueeDQeO4f0AApX3CvIM0KOATyeKGIT7Eug8znjPpD2pUYtVeHS87O6aySgRXd0aXc2uLiP40JQeuba2SKQe9BOaxy7kvBhc94atdFN2LqtKKNAEx6cCG/j+T2plMLUMb6zg28tNqtaRjoQdwMld08uKpItkEN34zCO/hSEWk7lp7umwl2HpdCa9BjEIlzgeO1Fkck8hd9ShUnwCDTqSop+tR7jRi7KwKAbV3EJgzD5/TXicHxFu44GCElMJk/STiCy5IxyxslTf6BliUc1iGqe3o+/0+XIdS6oOEkQXhBonfMnXngRizRpUDjuhYI9fnGq2BZPwammaiFu0Ydc93dzL7GqL/2vhs77c9kUN34urjo9YKSSTGaGI2+Un++91zNFWrrUG3j/xmXD5PocxH4zKw5c/wyTDrC3kG+vQmBBN0d67ruVtTYmBd0h0sRaqe8XNkCpoM56UmggxV4vQkkYWAD7c82bu6LZUD0CTanNd5LHrskNjsxi6auE4RGTaKg9mTzVcdoGWCDdb3RIh28tJLsBCfWw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
