travis:
  secure:
    BINSTAR_TOKEN: FzmLSVlVWxT8Bn9W0U00VZf4Xze+5L3X99YjwX0cQ+Z73ztqS9hswdf4jo/GszpG0EtOvXHYXjdC+Rig31+9ltOFTkWhWWWg77w1u4Li36l6dEZ3jTuJDOXCOg18PXEyVayoZSQthTaJdtOVOoL1Q9K9QXTTLKRXDE8xKBbUrVu4BF5SmxBOswUSagF4gogxhLNue1lOjE3Mksap+zvI6joK4i3przCv/f1MbPi8p8VTUPmVIa2LENqynVVyiKPa5nImVdieH0Uh6b9XnVpxhonGcWFfu2GH419Zn3HjL9D+78hH1vkS4PGjlEJ+ZmXYdG2rYfWaGfjD7T9UVRf9FlZILFyySxgnEB67+4L+P2n8JgdXo6A0MNgQVjE2tSsvBWgzmde4Wd+swDkQmSumL4ZX4bjgIz68Jrq3e44O/DR6qAM/MTPWAqUUEvi25DYTmREVNAtXTpBLpx01qBvfBAlZMYT25V0E9QamEL5q8P3HUzfYrvtX42+jGftL2doAruvPpBvrwMdESX5Zd1p+WRCrMED6a2d7TRnMEEH+EsMlv4ynkk3OmtssUrCu5ytW4tOqslS5CnYqNqdU9ajXTTCkEaZiO7Og7F7wIrq53mGwv6Twa7BgX6qIPu8Q4mpkOkIrbK7Fcpk8OklhPqRANFhVoze8hGLMkBgmSfrvWBk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
