travis:
  secure:
    BINSTAR_TOKEN: wKNQ2tT/J3dQxJ2x7cd+Hv8FDNoV9EY2Bnset2tPwDmqH39/jDq5ej0kag6H/YYYBkzVDWDfSGStiDB6pC/Y/g/nzLWHpgCaRdyZN4wB+EHhrxaHNiaiH7dO0Q3d5t4EQ1wrzoWNc4prJSGvoOLEyMPDqsT2tFlc1zB9MukM64F7DdLS/ZWzIN1pnRLdxQ8hrXl1lTL9d0PeGkxIyGS3v+OW277gxGBSp89/DKL/oRlQQuJpQ/7KcP78jjcf89+VafSx43zbViaz6GB34+4aSEoqLVIzR99xmw12jSVUPH4kLjjy6BIAfk0DYXmyNhEajjnz6QSxGLRvemh2t1pI+YjFIrnViuyxIX2bqjZLbKBCFs2fMWQpFgL399l6Q2P+8hHFswIVCoHUJE3YwUirZ7a70FRwDguk7eHf7bUhyzdsYag8gA6zfaQUqGfiICt0BorgIq8m6oTKqfadorlw6GlSQvp89QfRWzycbo7KkywH2WrUlVXh9aZT0ns2cq4/DYSIeHyvi+RplrbUGT3QXW4cJRztkMeZ33qqPwYVjvbP+bq5NbrqdB2KJR61l/WTNwOOfqwT8G9c3wSLAwFnrS+ZyCqCubIhcnW9fYizrdPzxnJZAKPYgc6zrVgnQ7OgNvuzqP6DUn3kG2tTpLNgMNEBC04BImzz8DeFF6v80yo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
